# =============== SERVICE NAME ===============
service: portfolio-backend-aws

# =============== PROVIDER CONFIG ===============

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

  environment:
    NODE_ENV: ${opt:stage, 'dev'}
    SERVICE_NAME: portfolio-backend

  httpApi:
    cors: true
    #   allowedOrigins:
    #     - https://your-portfolio.vercel.app
    #     - http://localhost:3000

# =============== FUNCTIONS ===============

functions:
  # GET https://api-id.execute-api.us-east-1.amazonaws.com/dev/
  health:
    handler: src/handlers/health.handler
    events:
      - httpApi:
          path: /
          method: get

  # POST https://api-id.execute-api.us-east-1.amazonaws.com/dev/contact
  contact:
    handler: src/handlers/contact.handler
    events:
      - httpApi:
          path: /contact
          method: post

    environment:
      CONTACT_TABLE: contacts-${sls:stage}

# =============== PLUGINS ===============
plugins:
  - serverless-offline

# =============== CUSTOM CONFIG ===============
custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
